---
- name: Run DB migrations
  shell: docker-compose run --rm web rails db:migrate
  args:
    chdir: "{{ mastodon_private }}"
  when: git_clone.changed
  
- name: Compile assets
  shell: docker-compose run --rm web rails assets:precompile
  args:
    chdir: "{{ mastodon_private }}"
  when: git_clone.changed
  
- name: Start the Mastodon service
  systemd:
    name: docker-mastodon
    state: started
    enabled: yes
