---
- hosts: mastodon
  gather_facts: False
  user: root

  tasks:
    - name: Install Python 2 if needed
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: install_python
      changed_when: "'Setting up python' in install_python.stdout"

    - name: Create the admin user
      user:
        name: "{{ admin_username }}"
        state: present
        comment: "{{ admin_realname }}"
        password: "{{ ansible_become_pass | password_hash('sha512') }}"
        append: yes
        groups:
          sudo

    - name: Install your SSH public key for the admin user
      authorized_key:
        user: "{{ admin_username }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Disable root SSH
      replace:
        name: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin yes$"
        replace: "PermitRootLogin no"
        validate: "/usr/sbin/sshd -t -f %s"
        backup: yes
      register: disable_root_ssh

    - name: Restart SSH
      systemd:
        name: ssh
        state: reloaded
      when: disable_root_ssh.changed
