---
- hosts: mastodon
  vars:
    pg_dir: /var/lib/postgresql
    device_file: /dev/disk/by-id/scsi-0DO_Volume_{{ block_device_name }}
  user: root

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install bootstrapping packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        python-minimal

    - name: Create the admin user
      user:
        name: "{{ admin_username }}"
        state: present
        comment: "{{ admin_realname }}"
        password: "{{ ansible_become_pass | password_hash('sha512') }}"
        append: yes
        groups:
          sudo

    - name: Create user "mastodon"
      user:
        name: mastodon
        state: present
        comment: "Mastodon"
        generate_ssh_key: yes
        ssh_key_comment: "mastodon@{{ ansible_host }}"

    - name: Install your SSH public key for the admin user
      authorized_key:
        user: "{{ admin_username }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Format the volume
      shell: mkfs.ext4 -F {{ device_file }}

    - name: Make the PostgreSQL directory
      file:
        path: "{{ pg_dir }}"
        state: directory

    - name: Mount the volume
      mount:
        fstype: ext4
        opts: defaults,nofail,discard
        src: "{{ device_file }}"
        name: "{{ pg_dir }}"
        state: mounted

    - name: Disable root SSH
      replace:
        name: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin yes$"
        replace: "PermitRootLogin no"
        validate: "/usr/sbin/sshd -t -f %s"
        backup: yes

    - name: Rebooting
      shell: reboot
