---
- name: Format the block device
  filesystem:
    dev: "{{ block_device_file }}"
    fstype: ext4
  when: block_device_file is defined

- name: Make the PostgreSQL directory
  file:
    path: "{{ pg_dir }}"
    state: directory

- name: Mount the PostgreSQL data volume
  mount:
    fstype: ext4
    opts: defaults,nofail,discard
    src: "{{ block_device_file }}"
    name: "{{ pg_dir }}"
    state: mounted
  when: block_device_file is defined

- name: Install PostgreSQL packages
  apt:
    name: postgresql-9.5
    state: present

- name: Configure PostgreSQL
  file:
    src: "{{ item }}"
    dest: /etc/postgresql/9.5/main/{{ item }}
  with_items:
    - pg_hba.conf
    - postgresql.conf
  register: postgresql_config

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted
  when: postgresql_config.changed

# This is so sketch, but PostgreSQL can try to start before Docker and
# not be able to bind to its interface. When that happens, PostgreSQL
# exits. This tries to start it again after 10 seconds. Nothing like
# good ol' determinism!
- name: Set PostgreSQL to start a few seconds after reboot
  cron:
    name: Start PostgreSQL after Docker settles
    special_time: reboot
    job: sleep 10 && /usr/sbin/service postgresql start

